version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: financas_postgres
    environment:
      POSTGRES_USER: vanessa
      POSTGRES_PASSWORD: senha_secreta_123
      POSTGRES_DB: financas_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: